# fly.toml app configuration file generated for api-portfolio-back on 2023-07-12T23:14:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-portfolio-back"
primary_region = "gru"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
